### ISSUE TITLE
DeepChess With python-chess Win7 

### ISSUE THREAD

**Issue by brianprichardson** [niklasf/python-chess#168]
Hi.  May not be a python-chess issue, but thought I might ask...

Working under Windows 7.
Trying to run DeepChess which needs python-chess.
There are several operations: playing games, training, and creating training data from a pgn.
DeepChess training  needs tensorflow.
Tensorflow on Windows needs python 3.5+ (I am using 3.6)

Trying the get_data.py routine with a small version of CCRL.pgn (about 56MB with roughly 50,000 games).  It works with Python 2.7.12, but not with Python 3.6.2.  Here is the error: 

C:\Users\Brian\AppData\Local\Programs\Python\Python36\DeepChess-master>py -3 get_data.py
Traceback (most recent call last):
  File "get_data.py", line 134, in <module>
    iterateOverFile()
  File "get_data.py", line 85, in iterateOverFile
    whiteIndex = addGameData(g, whiteWins, whiteIndex)
  File "get_data.py", line 66, in addGameData
    curIndex = traverse(game, picked, arr, curIndex)
  File "get_data.py", line 38, in traverse
    move = node.main_line().next()
AttributeError: 'generator' object has no attribute 'next'

Ultimately, I would like to create a new model.pkl trained file using Python 3.6.  The model with the download was created with Python 2, which cannot be read properly with Python 3, and I need Python 3 to do the training with tensorflow under Windows.

Separately, I am still trying to get the pre-built model.pkl Python 2 file to work under Windows.

Thank you.

**Comment by niklasf** [comment]
Hi, looks like a Python 2/3 incompability in `get_data.py`:

In Python 2 this works:

```
>>> def gen():
...     yield 42
... 
>>> gen().next()
42
```

In Python 3:

```
>>> def gen():
...     yield 42
... 
>>> gen().next()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'generator' object has no attribute 'next'
```

The fix would be writing `move = next(node.main_line())` instead of `move = node.main_line().next()`. Of course there might be other issues down the line ...

**Comment by brianprichardson** [comment]
Thank you for taking the time to look at this.  I have gotten it to work after more Python 2 to 3 tweaks.
